repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-added-large-files
      args: ['--maxkb=4096']
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: flake8
-   repo: https://github.com/szebenyib/pre-commit-pytest
    rev: 051fea31dbabf063ab38428c34a92c76d1abd5dc  # Use the sha / tag you want to point at
    hooks:
    -   id: pytest
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2 # Update me!
    hooks:
    - id: bandit
      args: ["--ini", ".bandit", "-x", "test/*"]
